let
  URL = "https://login.microsoftonline.com",
  Body = "grant_type=client_credentials&client_id=YOUR_CLIENT_ID&client_secret=YOUR_CLIENT_SECRET&resource=https%3A%2F%2Fgraph.microsoft.com%2F",
  Options = [
        Headers = [
            #"Content-Type" = "application/x-www-form-urlencoded"
        ],
        RelativePath = "/YOUR_TENANT_DOMAIN_NAME/oauth2/token?api-version=1.0",
        Content = Text.ToBinary(Body),
        Timeout = #duration(0,0,5,0)
    ],
  tokenResponse = Web.Contents(URL, Options),
  #"Imported JSON" = Json.Document(tokenResponse, 65001),
  access_token = #"Imported JSON"[access_token],
  token = "Bearer " & #"Imported JSON"[access_token],
  GetJsonQuery = OData.Feed("https://graph.microsoft.com/v1.0/groups", null, [ Implementation="2.0", Headers=[Authorization=token]  ]),
  #"Expanded members" = Table.ExpandTableColumn(GetJsonQuery, "members", {"id", "deletedDateTime"}, {"members.id", "members.deletedDateTime"}),
  #"Expanded groupTypes" = Table.ExpandListColumn(#"Expanded members", "groupTypes"),
  #"Removed Other Columns" = Table.SelectColumns(#"Expanded groupTypes", {"id", "members.id"})
in
  #"Removed Other Columns"
